/**
 * Placeholder File. DO NOT EDIT this file. Create your own file. 
 * @author jddevaughnbrown
 *
 */
public class Test {
	public static void main(String[] args) {
		System.out.println("Hello World");
		}
}
